#ifndef CXEFLASHDEFINES_H_
#define CXEFLASHDEFINES_H_

// lengths and sizes
#define XE_FLASH_PAGE_LENGTH 0x200
#define XE_FLASH_SPARE_LENGTH 0x10
#define XE_FLASH_PAGE_LENGTH_REAL XE_FLASH_PAGE_LENGTH+XE_FLASH_SPARE_LENGTH
#define XE_FLASH_PAGES_PER_BLOCK 0x20
#define XE_FLASH_BLOCK_LENGTH XE_FLASH_PAGE_LENGTH * XE_FLASH_PAGES_PER_BLOCK
#define XE_FLASH_BLOCK_LENGTH_REAL XE_FLASH_PAGE_LENGTH_REAL * XE_FLASH_PAGES_PER_BLOCK
#define XE_FLASH_BLOCKS_PER_BIG_BLOCK 4
#define XE_FLASH_BIG_BLOCK_LENGTH XE_FLASH_BLOCK_LENGTH * XE_FLASH_BLOCKS_PER_BIG_BLOCK
#define XE_FLASH_BIG_BLOCK_LENGTH_REAL XE_FLASH_BLOCK_LENGTH_REAL * XE_FLASH_BLOCKS_PER_BIG_BLOCK

#define XE_FLASH_PATCHSLOT_LENGTH 0x10000
#define XE_FLASH_BIG_PATCHSLOT_LENGTH 0x20000
#define XE_FLASH_FS_ENTRY_LENGTH sizeof(FLASHFILESYSTEM_ENTRY)
#define XE_FLASH_FS_CHAIN_ENTRY_LENGTH 2

#define XE_FLASH_16MB_LENGTH XE_FLASH_BLOCK_LENGTH * 0x400
#define XE_FLASH_64MB_LENGTH XE_FLASH_BLOCK_LENGTH * 0x1000
#define XE_FLASH_16MB_LENGTH_REAL XE_FLASH_BLOCK_LENGTH_REAL * 0x400
#define XE_FLASH_64MB_LENGTH_REAL XE_FLASH_BLOCK_LENGTH_REAL * 0x1000
#define XE_FLASH_256MB_LENGTH 0x1111

#define XE_FLASH_FS_BLOCK_TYPE 0x30
#define XE_FLASH_FS_BIG_BLOCK_TYPE 0x2F // TODO: ?


#define XE_FLASH_CORONA_FS_DATA_ADDR 0x2FE8000
#endif